### ISSUE TITLE
Include opacity option for ColorChooser

### ISSUE THREAD

**Issue by mbastian** [timboudreau/colorchooser#1]
Hi @timboudreau and thanks for this great library. We've been using it for years in https://github.com/gephi/gephi! We're still at the version 1.2 but I'm looking to update to the latest 1.4.

One thing I like is that it opens a ColorPicker on right click. But I couldn't figure out how one could include the **opacity**? I couldn't find a parameter or anything I can pass to the ColorChooser to indicate that the ColorPicker should include opacity.

### Potential solution

Maybe add a `includeOpacity` parameter in the ColorChooser.

Much appreciated!

**Comment by timboudreau** [comment]
Happy to see it used somewhere - it's the first Java code I ever wrote, circa 1999 :-)

I believe there *is* a key combination somewhere in there that lets you set opacity.  Not that I remember what it is...

**Comment by timboudreau** [comment]
There is an [AlphaPalette](https://github.com/timboudreau/colorchooser/blob/master/src/main/java/net/java/dev/colorchooser/AlphaPalette.java).

Right-drag to pop that up in the current sources.

**Comment by timboudreau** [comment]
(that's in the 1.4 sources)

**Comment by timboudreau** [comment]
FYI, I just released a 1.5 version on maven central that eliminates a few printlns that were still in the alpha palette code and might have been annoying.  Going to close this, since the feature works.

**Comment by mbastian** [comment]
Thanks for the 1.5 release! I didn't know about the alpha palette and it's definitely a good workaround. My use-case was however rather on the right-click. Sorry if that wasn't clear. Essentially, even with an alpha configured the right click looks like 
<img width="534" alt="Screenshot 2023-03-20 at 22 13 17" src="https://user-images.githubusercontent.com/234813/226467634-5195989b-dbe1-4646-9a00-594290501e51.png">

while I would hope the opacity slider included
<img width="532" alt="Screenshot 2023-03-20 at 22 16 53" src="https://user-images.githubusercontent.com/234813/226467950-36dfa5a3-d6fa-411c-8b69-adfc08189fc9.png">

Thanks in advance! Once again, it's a great library that drives color choosing in many places in Gephi.

**Comment by timboudreau** [comment]
FYI, you can pass your own array of palettes to the constructor if you want the alpha palette to be available from a different key combination.
